### ISSUE TITLE
Update links to other webapps

### ISSUE THREAD

**Issue by esune** [bcgov/dts-safe-entry-demo#15]
Links pointing to OCP3 deployments of services will need to be updated once the `prod` instances are migrated to OCP4.

[Here](https://github.com/bcgov/dts-safe-entry-demo/search?q=pathfinder) is a list of URLs that need changing:
- the URL in `config.json` can actually be removed
- the `identity-kit` URL will need to be updated with a new OCP4-suffixed URL

[This issue](https://github.com/bcgov/essential-services-delivery/issues/99) tracks the changes to the deployments.

**Comment by wadeking98** [comment]
links working in prod
