### ISSUE TITLE
Decommissioning demo deployments

### ISSUE THREAD

**Issue by esune** [bcgov/dts-safe-entry-demo#58]
In order to decommission the demo, we need to complete the following steps:
- [x] remove references from public-facing the [BC Digital Trust website](https://digital.gov.bc.ca/digital-trust/) (@alexgmetcalf )
- [x] save a back-up of the agent wallets (@WadeBarnes / @esune)
- [x] spin down the deployments (@WadeBarnes / @esune )
- [x] remove configurations from OCP (@WadeBarnes / @esune / @rajpalc7 )
- [x] close this issue (@WadeBarnes / @esune )
- [x] archive this repository (@WadeBarnes / @esune )

**Comment by alexgmetcalf** [comment]
References removed from website

**Comment by esune** [comment]
@WadeBarnes @rajpalc7 wallets have been backed-up and deployments spun down in all environments. Everything is ready for resources to be freed.
